name: PR Formatter for akka-http on push

on:
  push:
    branches:
      - test-gh-actions
jobs:
  sbt:
    name: Format PR for akka-http
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Set up JDK 8
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8.0

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.2

      - name: Format
        run: |-
          sbt -jvm-opts .jvmopts-ci \
            -Dakka.genjavadoc.enabled=true \
            -Dakka.test.timefactor=2 \
            -Dakka.cluster.assert=on \
            -Dsbt.override.build.repos=false \
            -Dsbt.log.noformat=false \
            headerCreate test:headerCreate scalariformFormat test:scalariformFormat

      - name: Check auto-formatted files
        run: |-
          (git diff --exit-code --color && git diff --cached --exit-code --color) || { 
            set +x 
            git config --global user.email "debasish.ghosh@lightbend.com"
            git config --global user.name "Debasish Ghosh"
            git remote remove pr-origin || true 
            git remote add pr-origin https://github.com/${{github.repository}}.git  
            git push pr-origin HEAD:${{github.ref}} 
          }

      - name: Check for generated mima exclusion files
        run: |-
          git add **/mima-filters/*.excludes 
          git diff --cached --exit-code --color || { 
            set +x
            git commit --author="Akka Jenkins <johannes.rudolph@gmail.com>" -a -m "Autogenerated mima excludes, please pull your branch and edit them manually"
            git remote remove pr-origin || true 
            git remote add pr-origin https://github.com/${{github.repository}}.git 
            git push pr-origin HEAD:${{github.ref}} 
          }	
